---
- name: Install and start docker image "ombt" in client mode
  docker_container:
    image: beyondtheclouds/ombt
    command: "--debug --control rabbit://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }}
         --url {{ transport }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }} rpc-client"
    name: "ombt-client-{{ item }}"
    detach: True
    network_mode: host
    state: started
  when: inventory_hostname in groups['ombt-client'] and ombt_args=="rpc-client"
  with_sequence: count={{ nbr_clients }}

- name: Install and start docker image "ombt" in server mode
  docker_container:
    image: beyondtheclouds/ombt
    command: "--debug --control rabbit://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }}
         --url {{ transport }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }} rpc-server"
    name: "ombt-server-{{ item }}"
    detach: True
    network_mode: host
    state: started
  when: inventory_hostname in groups['ombt-server'] and ombt_args=="rpc-server"
  with_sequence: count={{ nbr_servers }}

- name: Install and start docker image "ombt" as a controller
  docker_container:
    image: beyondtheclouds/ombt
    command: "--debug --control rabbit://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }}
         --url {{ transport }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}:{{ rabbitmq_port }} controller {{ call_type }} --calls {{ nbr_calls }} --pause {{ pause }} "
    name: ombt-controller
    detach: False
    network_mode: host
    state: started
  when: inventory_hostname in groups['ombt-control'] and ombt_args=="controller"