---
- name: Install and start docker image "ombt" in client mode
  shell: >
         docker run -d -ti beyondtheclouds/ombt
         --debug --control {{ broker }}://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}
         --url {{ broker }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }} rpc-client
  when: inventory_hostname in groups['ombt-client']

- name: Install and start docker image "ombt" in server mode
  shell: >
         docker run -d -ti beyondtheclouds/ombt
         --debug --control {{ broker }}://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}
         --url {{ broker }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }} rpc-server
  when: inventory_hostname in groups['ombt-server']

- name: Install and start docker image "ombt" as a controller
  shell: >
         docker run -d -ti beyondtheclouds/ombt
         --debug --control {{ broker }}://{{ hostvars[groups['control-bus'][0]]['ansible_' + control_network]['ipv4']['address'] }}
         --url {{ broker }}://{{ hostvars[groups['bus'][0]]['ansible_' + control_network]['ipv4']['address'] }} controller rpc-call --calls 10
  when: inventory_hostname in groups['ombt-control']
