---
- name: Common configuration
  hosts: all
  roles:
    - common
    - registry
    - telegraf

- name: Apply role chrony
  hosts:
    - chrony-server
    - chrony
  roles:
    - chrony

- name: Deploy prometheus
  hosts: prometheus
  roles:
    - prometheus

- name: Deploy the grafana
  hosts: grafana
  roles:
    - grafana
#
#- name: Deploy Control-bus
#  hosts: control-bus
#  roles:
#    - rabbitmq
